name: ci

on: [push, pull_request]

jobs:
  ci-macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        swoole: [4.6]

    env:
      MYSQL_SERVER_PASSWORD: ""

    steps:
      - uses: actions/checkout@v2

      - name: install db
        run: |
          brew install mysql redis
          brew services start mysql
          brew services start redis
      - name: install php
        run: .github/macos/install-php7.4-mac.sh
      - name: install swoole
        run: sudo .github/macos/install-swoole4.6.sh
      - name: prepare
        run: |
          composer update
          mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS db_imi_test;'
          tests/db/install-db.sh
      - name: test
        run: |
          composer test

  ci-php8-jit:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        swoole: [4.6-php8.0, 4.5-php8.0]
        mysql: [8.0]
    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}
      MYSQL_DOCKER_VERSION: ${{ matrix.mysql }}
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          ./.github/prepare-test.sh swoole-php8
      - name: test
        run: docker exec swoole-php8 composer test
      - name: test components
        run: docker exec swoole-php8 composer test-components
      - name: print logs
        if: failure()
        run: docker exec swoole-php8 php .github/print-logs.php

  ci-php:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        swoole:
          [
            4.6-php7.2,
            4.6-php7.3,
            4.6-php7.4,
            4.6-php8.0,
            4.5-php7.1,
            4.5-php7.2,
            4.5-php7.3,
            4.5-php7.4,
            4.5-php8.0,
            4.4-php7.1,
            4.4-php7.2,
            4.4-php7.3,
            4.4-php7.4,
          ]
        mysql: [5.7, 8.0]
    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}
      MYSQL_DOCKER_VERSION: ${{ matrix.mysql }}
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          ./.github/prepare-test.sh swoole
      - name: test
        run: docker exec swoole composer test
      - name: test components
        run: docker exec swoole composer test-components
      - name: print logs
        if: failure()
        run: docker exec swoole php .github/print-logs.php
