name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        swoole:
          [
            4.5.8-php7.1,
            4.5.8-php7.2,
            4.5.8-php7.3,
            4.5.8-php7.4,
            4.4.22-php7.1,
            4.4.22-php7.2,
            4.4.22-php7.3,
            4.4.22-php7.4,
            4.3.6-php7.1,
            4.3.6-php7.2,
            4.3.6-php7.3,
          ]
        mysql: [5.7, 8.0]

    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}
      MYSQL_DOCKER_VERSION: ${{ matrix.mysql }}

    steps:
      - uses: actions/checkout@v1

      - name: prepare
        run: |
          ./.github/prepare-test.sh swoole

      - name: test
        run: docker exec swoole php tests/run

  ci-php8:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        swoole: [4.5.9-php8.0]
        mysql: [5.7, 8.0]

    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}
      MYSQL_DOCKER_VERSION: ${{ matrix.mysql }}

    steps:
      - uses: actions/checkout@v1

      - name: prepare
        run: |
          ./.github/prepare-test.sh php8

      - name: test
        run: docker exec php8 php tests/run

  ci-macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        swoole: [4.5]

    steps:
      - uses: actions/checkout@v1

      - name: install php
        run: sudo .github/macos/install-php7.4-mac.sh

      - name: install swoole
        run: sudo .github/macos/install-swoole4.5.sh

      - name: composer
        run: |
          composer update
          cd tests
          composer update

      - name: test
        run: |
          sudo composer test
