name: Markdownlint

on:
  push:
      paths:
        - 'doc/**'
        - '.markdownlint.json'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          npm install

      - name: Markdownlint
        run: ./node_modules/.bin/markdownlint -f ./doc
