name: Coding Standards

on:
  push:
    paths-ignore:
      - "doc/**"
      - "mddoc/**"
      - "res/**"
      - "website/**"
      - ".markdownlint.json"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      SWOOLE_DOCKER_VERSION: 4.8-php7.4
      POSTGRESQL_VERSION: v4.8.0
      ENV_SERVICE: swoole-only
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker-compose -f ./.github/docker-compose.yml up -d ${ENV_SERVICE}
          docker exec ${ENV_SERVICE} php -v
          docker exec ${ENV_SERVICE} composer -V
          docker exec ${ENV_SERVICE} composer update --no-interaction --prefer-dist --no-progress
          docker exec ${ENV_SERVICE} bash -c "cd split-repository && composer install --no-interaction --prefer-dist --no-progress"

      - name: Coding Standards Tests
        run: docker exec ${ENV_SERVICE} ./vendor/bin/php-cs-fixer fix --dry-run --diff -vvv
