name: Coding Standards

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      php-versions: 8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          tools: pecl, composer:v2
          extensions: redis, swoole, inotify
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --ignore-platform-reqs --no-scripts

      - name: Coding Standards Tests
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
