name: Static Code Analysis

on:
  push:
    paths-ignore:
      - "doc/**"
      - "mddoc/**"
      - "res/**"
      - "website/**"
      - ".markdownlint.json"
      - "README.md"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swoole-docker: [php8.1-swoole-5.0]
    env:
      REPOSITORY_OWNER: ${{ github.repository_owner }}
      IMAGE_VERSION: ${{ matrix.swoole-docker }}
      ENV_SERVICE: swoole-only
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare#1
        run: |
          echo "REPOSITORY_OWNER=${REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
          mkdir -p /tmp/base_cache/composer
          mkdir -p /tmp/base_cache/phpstan

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/base_cache/composer
          key: ${{ runner.os }}-composer-${{ env.IMAGE_VERSION }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ env.IMAGE_VERSION }}-
            ${{ runner.os }}-composer-

      - name: Prepare
        run: |
          echo "::group::Env prepare"
          docker-compose -f ./.github/docker-compose.yml up -d ${ENV_SERVICE}
          docker exec ${ENV_SERVICE} rm -rf /tmp/phpstan
          docker exec ${ENV_SERVICE} ln -sf /tmp/base_cache/phpstan /tmp
          echo "::endgroup::"
          echo "::group::Env info"
          docker exec ${ENV_SERVICE} php -v
          docker exec ${ENV_SERVICE} php -m
          docker exec ${ENV_SERVICE} php --ri swoole
          docker exec ${ENV_SERVICE} composer -V
          echo "::endgroup::"
          echo "::group::Composer install"
          docker exec ${ENV_SERVICE} composer config --global cache-files-dir /tmp/base_cache/composer
          docker exec ${ENV_SERVICE} composer update --no-interaction --prefer-dist --no-progress
          docker exec ${ENV_SERVICE} bash -c "cd split-repository && composer install --no-interaction --prefer-dist --no-progress"
          echo "::endgroup::"
          echo "test_prepared=1" >> $GITHUB_ENV

      - name: Cache phpstan
        uses: actions/cache@v3
        with:
          path: /tmp/base_cache/phpstan
          key: ${{ runner.os }}-phpstan-${{ env.IMAGE_VERSION }}-${{ hashFiles('**/phpstan.neon', '**/phpstan-components.neon', '**/phpstan-baseline/*.neon', '**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-phpstan-${{ env.IMAGE_VERSION }}-
            ${{ runner.os }}-phpstan-

      - name: Analyse core
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh core

      - name: Analyse amqp
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh amqp

      - name: Analyse apidoc
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh apidoc

      - name: Analyse fpm
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh fpm

      - name: Analyse grpc
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh grpc

      - name: Analyse jwt
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh jwt

      - name: Analyse kafka
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh kafka

      - name: Analyse mqtt
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh mqtt

      - name: Analyse pgsql
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh pgsql

      - name: Analyse queue
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh queue

      - name: Analyse rate-limit
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh rate-limit

      - name: Analyse roadrunner
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh roadrunner

      - name: Analyse rpc
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh rpc

      - name: Analyse shared-memory
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh shared-memory

      - name: Analyse smarty
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh smarty

      - name: Analyse snowflake
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh snowflake

      - name: Analyse swoole
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh swoole

      - name: Analyse swoole-tracker
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh swoole-tracker

      - name: Analyse workerman
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh workerman

      - name: Analyse workerman-gateway
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh workerman-gateway

      - name: Analyse phar
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./dev/phpstan.sh phar

      - name: Test
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ls -lha /tmp
          docker exec ${ENV_SERVICE} ls -lha /tmp/phpstan
          docker exec ${ENV_SERVICE} ls -lha /tmp/base_cache
          docker exec ${ENV_SERVICE} ls -lha /tmp/base_cache/phpstan
