name: Static Code Analysis

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      php-versions: 7.4
      extensions: sockets, curl
      ext-key: cache-v1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.ext-key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          tools: pecl, composer:v2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Swoole
        run: |
          apt-fast install libcurl4-openssl-dev -y
          sudo pecl update-channels
          MAKEFLAGS="-j $(nproc)" sudo -E sudo pecl install -f \
            -D ' \
              enable-openssl="yes" enable-sockets="yes" enable-http2="yes" \
              enable-swoole-json="yes" enable-swoole-curl="yes"  \
            ' \
            swoole

      - name: Show Version
        run: |
          composer -V
          php -m
          php --ri swoole

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ env.php-versions }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ env.php-versions }}-
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress
          cd ./split-repository
          composer install --prefer-dist --no-progress

      - name: Cache Analyse
        uses: actions/cache@v2
        with:
          path: /tmp/phpstan
          key: phpstan-analyse
          restore-keys: phpstan-analyse

      - name: Analyse
        run: ./vendor/bin/phpstan analyse --memory-limit 1G
