name: Static Code Analysis

on:
  push:
    paths-ignore:
      - "doc/**"
      - "mddoc/**"
      - "res/**"
      - "website/**"
      - ".markdownlint.json"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        swoole-docker: [4.8-php7.4]
    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole-docker }}
      POSTGRESQL_VERSION: v4.8.0
      ENV_SERVICE: swoole-only
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker-compose -f ./.github/docker-compose.yml up -d ${ENV_SERVICE}
          docker exec ${ENV_SERVICE} php -v
          docker exec ${ENV_SERVICE} php -m
          docker exec ${ENV_SERVICE} php --ri swoole
          docker exec ${ENV_SERVICE} composer -V
          docker exec ${ENV_SERVICE} composer update --no-interaction --prefer-dist --no-progress
          docker exec ${ENV_SERVICE} bash -c "cd split-repository && composer install --no-interaction --prefer-dist --no-progress"
          echo "test_prepared=1" >> $GITHUB_ENV

      - name: Analyse core
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G

      - name: Analyse access-control
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/access-control/vendor/autoload.php src/Components/access-control

      - name: Analyse amqp
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/amqp/vendor/autoload.php src/Components/amqp

      - name: Analyse apidoc
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/apidoc/vendor/autoload.php src/Components/apidoc

      - name: Analyse fpm
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/fpm/vendor/autoload.php src/Components/fpm

      - name: Analyse grpc
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/grpc/vendor/autoload.php src/Components/grpc

      - name: Analyse jwt
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/jwt/vendor/autoload.php src/Components/jwt

      - name: Analyse kafka
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/kafka/vendor/autoload.php src/Components/kafka

      - name: Analyse mqtt
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/mqtt/vendor/autoload.php src/Components/mqtt

      - name: Analyse pgsql
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/pgsql/vendor/autoload.php src/Components/pgsql

      - name: Analyse queue
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/queue/vendor/autoload.php src/Components/queue

      - name: Analyse rate-limit
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/rate-limit/vendor/autoload.php src/Components/rate-limit

      - name: Analyse roadrunner
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/roadrunner/vendor/autoload.php src/Components/roadrunner

      - name: Analyse rpc
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/rpc/vendor/autoload.php src/Components/rpc

      - name: Analyse shared-memory
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/shared-memory/vendor/autoload.php src/Components/shared-memory

      - name: Analyse smarty
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/smarty/vendor/autoload.php src/Components/smarty

      - name: Analyse snowflake
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/snowflake/vendor/autoload.php src/Components/snowflake

      - name: Analyse swoole
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/swoole/vendor/autoload.php src/Components/swoole

      - name: Analyse swoole-tracker
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/swoole-tracker/vendor/autoload.php src/Components/swoole-tracker

      - name: Analyse workerman
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/workerman/vendor/autoload.php src/Components/workerman

      - name: Analyse workerman-gateway
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/workerman-gateway/vendor/autoload.php src/Components/workerman-gateway

      - name: Analyse macro
        if: ${{ env.test_prepared && always() }}
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G --configuration=phpstan-components.neon --autoload-file=src/Components/macro/vendor/autoload.php src/Components/macro
